name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3.9 clang-11 libc++-11-dev libc++abi-11-dev
      - run: pip install meson
      - run: meson --version
      - run: export clang=clang-11
      - run: clang --version

  windows:
    runs-on: windows-latest
    steps:
      - run: choco install llvm python3
      - run: RefreshEnv
      - run: pip install meson
      - run: meson --version
      - run: clang-cl --version

  mac:
    runs-on: macos-latest
    steps:
      - run: brew install meson 
      - run: meson --version
      - run: clang --version
